import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/ui/Nav";
import Sidebar from "@/components/ui/Sidebar";
import MainContainer from "@/components/layout/MainContainer";
import Footer from "@/components/ui/Footer";
import MobileNav from "@/components/ui/MobileNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E Pharma",
  description: "Generated by Next Js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Nav />
        <MainContainer>
          <div className="flex gap-8 m-4 md:m-8">
            <div className="hidden lg:block">
              <Sidebar />
            </div>
            <div>{children}</div>
          </div>
        </MainContainer>
        <Footer />
        <div className="sticky bottom-0">
          <MobileNav />
        </div>
      </body>
    </html>
  );
}
